apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: speech-api
  name: speech-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: speech-api
  template:
    metadata:
      labels:
        run: speech-api
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: master-pool
      containers:
        - name: speech-api
          env:
            # This is the maximum time between recomputing the number of pods. This ensures that
            # pods are scaled down quickly if pods are no longer in-use.
            - name: AUTOSCALE_LOOP
              value: '15000' # 15 seconds in milliseconds
            # This is the time we look into the past to compute the number of resources needed for
            # the next time period.
            - name: AUTOSCALE_WINDOW
              value: '600000' # 10 minutes in milliseconds
            - name: MAXIMUM_PODS
              value: '100'
            - name: WORKER_POD_IMAGE
              value: gcr.io/mythical-runner-203817/speech-api-worker:v2.25
            - name: WORKER_POD_EXPOSED_PORT # Port master communicates with its workers on
              value: '8000'
            - name: WORKER_POD_PREFIX
              value: speech-api-worker-pod
            - name: WORKER_NODE_PREFIX
              value: speech-api-worker-node
            - name: WORKER_NODE_POOL
              value: worker-pool
            - name: MINIMUM_WORKER_PODS
              value: '1'
            # Percentage of extra additional pods for any spillover jobs.
            - name: EXTRA_WORKER_PODS
              value: '1.0'
            - name: API_KEY_SUFFIX # Pattern for discovering api keys
              value: _SPEECH_API_KEY
            - name: MATT_HOCKING_SPEECH_API_KEY # NOTE: Do not forget to create these secrets.
              valueFrom:
                secretKeyRef:
                  key: matt_hocking_api_key
                  name: speech-api-key
            - name: MICHAEL_PETROCHUK_SPEECH_API_KEY
              valueFrom:
                secretKeyRef:
                  key: michael_petrochuk_api_key
                  name: speech-api-key
            - name: WEB_BACKEND_SPEECH_API_KEY
              valueFrom:
                secretKeyRef:
                  key: web_backend_api_key
                  name: speech-api-key
            - name: WEB_BACKEND_SPEECH_API_KEY
              valueFrom:
                secretKeyRef:
                  key: web_backend_api_key
                  name: speech-api-key
            - name: THIS_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: THIS_POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: THIS_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: gcr.io/mythical-runner-203817/speech-api:v1.84
          ports:
            - containerPort: 8000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthy
              port: 8000
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 15
