apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: speech-api
  name: speech-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: speech-api
  template:
    metadata:
      labels:
        run: speech-api
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: master-pool
      containers:
        - name: speech-api
          env:
            # This is the maximum time between recomputing the number of pods. This ensures that
            # pods are scaled down quickly if pods are no longer in-use.
            - name: AUTOSCALE_LOOP
              value: "15000" # 15 seconds in milliseconds
            # This is the time we look into the past to compute the number of resources needed for
            # the next time period.
            - name: AUTOSCALE_WINDOW
              value: "1800000" # 30 minutes in milliseconds
            - name: MAXIMUM_PODS
              value: "100"
            - name: V1_WORKER_POD_IMAGE
              value: gcr.io/voice-service-255602/speech-api-worker:v1.06
            - name: V2_WORKER_POD_IMAGE
              value: gcr.io/voice-service-255602/speech-api-worker:v2.34
            - name: V3_WORKER_POD_IMAGE
              value: gcr.io/voice-service-255602/speech-api-worker:v3.02
            - name: WORKER_POD_EXPOSED_PORT # Port master communicates with its workers on
              value: "8000"
            - name: WORKER_POD_PREFIX
              value: speech-api-worker-pod
            - name: WORKER_NODE_POOL
              value: worker-pool
            - name: MINIMUM_WORKER_PODS
              value: "1"
            # Number of extra additional pods for any spillover jobs. Also this caps the growth
            # rate of the long term scaling because it is capped by the maximum number of pods that
            # existed within the `AUTOSCALE_WINDOW` time period.
            - name: EXTRA_WORKER_PODS
              value: "2"
            # Ensure there are enough resources for `COVERAGE`% of clips generated based on the
            # `AUTOSCALE_WINDOW`.
            - name: COVERAGE
              value: "0.90"
            - name: API_KEY_SUFFIX # Pattern for discovering api keys
              value: _SPEECH_API_KEY
            - name: MATT_HOCKING_SPEECH_API_KEY # NOTE: Do not forget to create these secrets.
              valueFrom:
                secretKeyRef:
                  key: matt_hocking_api_key
                  name: speech-api-key
            - name: MICHAEL_PETROCHUK_SPEECH_API_KEY
              valueFrom:
                secretKeyRef:
                  key: michael_petrochuk_api_key
                  name: speech-api-key
            - name: WEBSITE_BACKEND_SPEECH_API_KEY
              valueFrom:
                secretKeyRef:
                  key: website_backend_api_key
                  name: speech-api-key
            - name: THIS_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: THIS_POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: THIS_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: gcr.io/voice-service-255602/speech-api:v3.07
          ports:
            - containerPort: 8000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthy
              port: 8000
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 15
