# Note this error on using this YAML:
# https://stackoverflow.com/questions/44349987/error-from-server-forbidden-error-when-creating-clusterroles-rbac-author
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-creator
  namespace: default
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "nodes"]
  verbs: ["get", "create", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: create-pods
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: pod-creator
  apiGroup: ""
