# NTOE: This error on using this YAML:
# https://stackoverflow.com/questions/44349987/error-from-server-forbidden-error-when-creating-clusterroles-rbac-author
# NOTE: This needs to be `ClusterRole` instead of `Role` to `delete` a `node`; however, this
# also means that we cannot use namespaces.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-creator
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "nodes"]
  verbs: ["get", "create", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: create-pods
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: pod-creator
  apiGroup: ""
