dist: trusty
sudo: required

language: python
python:
  - '3.7.3'

cache: pip

notifications:
  email: false

install: source travis/install.sh
script: RUN_SLOW=true RUN_FLAKE8=true bash travis/test_script.sh
