dist: trusty
sudo: required

language: python
matrix:
  include:
    - python: 3.6
      dist: trusty
      sudo: false
    - python: 3.7
      dist: xenial
      sudo: true

cache: pip

notifications:
  email: false

install: source travis/install.sh
script: RUN_FLAKE8=true bash travis/test_script.sh
