[tool.black]
line-length = 100
target-version = ['py37']

[tool.isort]
profile = 'black'
src_paths = ['lib', 'tests', 'run']
line_length = 100

[tool.pytest.ini_options]
testpaths = ['lib', 'tests', 'run']
addopts = '--cov=lib --cov=run --cov-report html:coverage --cov-report=term-missing --durations=10'
filterwarnings = [
    'ignore::UserWarning:hparams.*:'
]

